name: Deploy

on:
  workflow_run:
    workflows: [ "Build" ]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy DockerImage using flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        run: flyctl deploy --local-only
